name: Build and Test

env:
  TERM: xterm-256color

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build
      run: nix-shell --run 'make all'

    - name: Test
      run: nix-shell --run 'make test'
